version: "3.7"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: phonebook_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Devenes_123
    volumes:
      - db-data:/var/lib/mysql
    configs:
      - source: table
        target: /docker-entrypoint-initdb.d/init.sql
    networks:
      - infraformnet

  app-server:
    env_file: .env
    image: "${ECR_REGISTRY}/${APP_REPO_NAME}:latest"
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first
    ports:
      - "80:80"
    networks:
      - infraformnet

networks:
  infraformnet:
    driver: overlay

volumes:
  db-data:

configs:
  table:
    file: ./init.sql